#############################################################################
# Makefile for building: myViewer
# Generated by qmake (3.0) (Qt 5.6.1)
# Project:  viewer.pro
# Template: app
# Command: /usr/bin/qmake-qt5 -o Makefile viewer.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../trimesh2/include -I../glm -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtOpenGL -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake-qt5
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = myViewer1.0.0
DISTDIR = /user/7/.base/duleryr/home/3A/Image_synthese/sytheseImage/viewer/.tmp/myViewer1.0.0
LINK          = g++
LFLAGS        = -Wno-unknown-pragmas -fopenmp -Wl,-O1 -Wl,-z,relro
LIBS          = $(SUBLIBS) -L../trimesh2/lib -ltrimesh -lglut -lGLEW -lQt5OpenGL -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/openglwindow.cpp \
		src/joint.cpp \
		src/glshaderwindow.cpp moc_openglwindow.cpp \
		moc_glshaderwindow.cpp
OBJECTS       = main.o \
		openglwindow.o \
		joint.o \
		glshaderwindow.o \
		moc_openglwindow.o \
		moc_glshaderwindow.o
DIST          = /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		viewer.pro src/openglwindow.h \
		src/glshaderwindow.h \
		src/joint.h \
		src/perlinNoise.h src/main.cpp \
		src/openglwindow.cpp \
		src/joint.cpp \
		src/glshaderwindow.cpp
QMAKE_TARGET  = myViewer
DESTDIR       = 
TARGET        = myViewer


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: viewer.pro /usr/lib64/qt5/mkspecs/linux-g++/qmake.conf /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		viewer.pro \
		/usr/lib64/libQt5OpenGL.prl \
		/usr/lib64/libQt5Widgets.prl \
		/usr/lib64/libQt5Gui.prl \
		/usr/lib64/libQt5Core.prl
	$(QMAKE) -o Makefile viewer.pro
/usr/lib64/qt5/mkspecs/features/spec_pre.prf:
/usr/lib64/qt5/mkspecs/common/unix.conf:
/usr/lib64/qt5/mkspecs/common/linux.conf:
/usr/lib64/qt5/mkspecs/common/sanitize.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt5/mkspecs/common/g++-base.conf:
/usr/lib64/qt5/mkspecs/common/g++-unix.conf:
/usr/lib64/qt5/mkspecs/qconfig.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_enginio.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_enginio_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib64/qt5/mkspecs/features/qt_functions.prf:
/usr/lib64/qt5/mkspecs/features/qt_config.prf:
/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib64/qt5/mkspecs/features/spec_post.prf:
/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt5/mkspecs/features/default_pre.prf:
/usr/lib64/qt5/mkspecs/features/resolve_config.prf:
/usr/lib64/qt5/mkspecs/features/default_post.prf:
/usr/lib64/qt5/mkspecs/features/warn_on.prf:
/usr/lib64/qt5/mkspecs/features/qt.prf:
/usr/lib64/qt5/mkspecs/features/resources.prf:
/usr/lib64/qt5/mkspecs/features/moc.prf:
/usr/lib64/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib64/qt5/mkspecs/features/uic.prf:
/usr/lib64/qt5/mkspecs/features/unix/thread.prf:
/usr/lib64/qt5/mkspecs/features/file_copies.prf:
/usr/lib64/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib64/qt5/mkspecs/features/exceptions.prf:
/usr/lib64/qt5/mkspecs/features/yacc.prf:
/usr/lib64/qt5/mkspecs/features/lex.prf:
viewer.pro:
/usr/lib64/libQt5OpenGL.prl:
/usr/lib64/libQt5Widgets.prl:
/usr/lib64/libQt5Gui.prl:
/usr/lib64/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile viewer.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib64/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/openglwindow.h src/glshaderwindow.h src/joint.h src/perlinNoise.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/openglwindow.cpp src/joint.cpp src/glshaderwindow.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib64/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2 -std=gnu++0x -Wall -W -dM -E -o moc_predefs.h /usr/lib64/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_openglwindow.cpp moc_glshaderwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_openglwindow.cpp moc_glshaderwindow.cpp
moc_openglwindow.cpp: src/openglwindow.h \
		moc_predefs.h
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/user/7/.base/duleryr/home/3A/Image_synthese/sytheseImage/viewer -I/user/7/.base/duleryr/home/3A/Image_synthese/sytheseImage/trimesh2/include -I/user/7/.base/duleryr/home/3A/Image_synthese/sytheseImage/glm -I/usr/include/qt5 -I/usr/include/qt5/QtOpenGL -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/4.8.5 -I/usr/include/c++/4.8.5/x86_64-redhat-linux -I/usr/include/c++/4.8.5/backward -I/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include -I/usr/local/include -I/usr/include src/openglwindow.h -o moc_openglwindow.cpp

moc_glshaderwindow.cpp: src/openglwindow.h \
		../trimesh2/include/TriMesh.h \
		../trimesh2/include/Vec.h \
		../trimesh2/include/Box.h \
		../trimesh2/include/strutil.h \
		../trimesh2/include/Color.h \
		src/joint.h \
		../glm/glm/glm.hpp \
		../glm/glm/detail/_fixes.hpp \
		../glm/glm/fwd.hpp \
		../glm/glm/detail/type_int.hpp \
		../glm/glm/detail/setup.hpp \
		../glm/glm/simd/platform.h \
		../glm/glm/detail/type_float.hpp \
		../glm/glm/detail/type_vec.hpp \
		../glm/glm/detail/precision.hpp \
		../glm/glm/detail/type_mat.hpp \
		../glm/glm/vec2.hpp \
		../glm/glm/detail/type_vec2.hpp \
		../glm/glm/detail/_swizzle.hpp \
		../glm/glm/detail/_swizzle_func.hpp \
		../glm/glm/detail/type_vec2.inl \
		../glm/glm/vec3.hpp \
		../glm/glm/detail/type_vec3.hpp \
		../glm/glm/detail/type_vec3.inl \
		../glm/glm/vec4.hpp \
		../glm/glm/detail/type_vec4.hpp \
		../glm/glm/detail/type_vec4.inl \
		../glm/glm/detail/type_vec4_simd.inl \
		../glm/glm/mat2x2.hpp \
		../glm/glm/detail/type_mat2x2.hpp \
		../glm/glm/detail/type_mat2x2.inl \
		../glm/glm/detail/func_matrix.hpp \
		../glm/glm/mat2x3.hpp \
		../glm/glm/detail/type_mat2x3.hpp \
		../glm/glm/detail/type_mat2x3.inl \
		../glm/glm/mat2x4.hpp \
		../glm/glm/detail/type_mat2x4.hpp \
		../glm/glm/detail/type_mat2x4.inl \
		../glm/glm/mat3x2.hpp \
		../glm/glm/detail/type_mat3x2.hpp \
		../glm/glm/detail/type_mat3x2.inl \
		../glm/glm/mat3x3.hpp \
		../glm/glm/detail/type_mat3x3.hpp \
		../glm/glm/detail/type_mat3x3.inl \
		../glm/glm/mat3x4.hpp \
		../glm/glm/detail/type_mat3x4.hpp \
		../glm/glm/detail/type_mat3x4.inl \
		../glm/glm/mat4x2.hpp \
		../glm/glm/detail/type_mat4x2.hpp \
		../glm/glm/detail/type_mat4x2.inl \
		../glm/glm/mat4x3.hpp \
		../glm/glm/detail/type_mat4x3.hpp \
		../glm/glm/detail/type_mat4x3.inl \
		../glm/glm/mat4x4.hpp \
		../glm/glm/detail/type_mat4x4.hpp \
		../glm/glm/detail/type_mat4x4.inl \
		../glm/glm/detail/type_mat4x4_simd.inl \
		../glm/glm/detail/func_matrix.inl \
		../glm/glm/geometric.hpp \
		../glm/glm/detail/func_geometric.hpp \
		../glm/glm/detail/func_geometric.inl \
		../glm/glm/detail/func_exponential.hpp \
		../glm/glm/detail/type_vec1.hpp \
		../glm/glm/detail/type_vec1.inl \
		../glm/glm/detail/func_exponential.inl \
		../glm/glm/detail/func_vector_relational.hpp \
		../glm/glm/detail/func_vector_relational.inl \
		../glm/glm/detail/func_vector_relational_simd.inl \
		../glm/glm/detail/_vectorize.hpp \
		../glm/glm/detail/func_exponential_simd.inl \
		../glm/glm/simd/exponential.h \
		../glm/glm/detail/func_common.hpp \
		../glm/glm/detail/func_common.inl \
		../glm/glm/detail/func_common_simd.inl \
		../glm/glm/simd/common.h \
		../glm/glm/detail/func_geometric_simd.inl \
		../glm/glm/simd/geometric.h \
		../glm/glm/detail/func_matrix_simd.inl \
		../glm/glm/simd/matrix.h \
		../glm/glm/trigonometric.hpp \
		../glm/glm/detail/func_trigonometric.hpp \
		../glm/glm/detail/func_trigonometric.inl \
		../glm/glm/detail/func_trigonometric_simd.inl \
		../glm/glm/exponential.hpp \
		../glm/glm/common.hpp \
		../glm/glm/packing.hpp \
		../glm/glm/detail/func_packing.hpp \
		../glm/glm/detail/func_packing.inl \
		../glm/glm/detail/type_half.hpp \
		../glm/glm/detail/type_half.inl \
		../glm/glm/detail/func_packing_simd.inl \
		../glm/glm/matrix.hpp \
		../glm/glm/vector_relational.hpp \
		../glm/glm/integer.hpp \
		../glm/glm/detail/func_integer.hpp \
		../glm/glm/detail/func_integer.inl \
		../glm/glm/detail/func_integer_simd.inl \
		../glm/glm/simd/integer.h \
		../glm/glm/gtc/matrix_transform.hpp \
		../glm/glm/gtc/constants.hpp \
		../glm/glm/gtc/constants.inl \
		../glm/glm/gtc/matrix_transform.inl \
		../glm/glm/gtc/type_ptr.hpp \
		../glm/glm/gtc/quaternion.hpp \
		../glm/glm/gtc/quaternion.inl \
		../glm/glm/gtc/quaternion_simd.inl \
		../glm/glm/gtc/type_ptr.inl \
		src/glshaderwindow.h \
		moc_predefs.h
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/user/7/.base/duleryr/home/3A/Image_synthese/sytheseImage/viewer -I/user/7/.base/duleryr/home/3A/Image_synthese/sytheseImage/trimesh2/include -I/user/7/.base/duleryr/home/3A/Image_synthese/sytheseImage/glm -I/usr/include/qt5 -I/usr/include/qt5/QtOpenGL -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/4.8.5 -I/usr/include/c++/4.8.5/x86_64-redhat-linux -I/usr/include/c++/4.8.5/backward -I/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include -I/usr/local/include -I/usr/include src/glshaderwindow.h -o moc_glshaderwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: src/main.cpp src/glshaderwindow.h \
		src/openglwindow.h \
		../trimesh2/include/TriMesh.h \
		../trimesh2/include/Vec.h \
		../trimesh2/include/Box.h \
		../trimesh2/include/strutil.h \
		../trimesh2/include/Color.h \
		src/joint.h \
		../glm/glm/glm.hpp \
		../glm/glm/detail/_fixes.hpp \
		../glm/glm/fwd.hpp \
		../glm/glm/detail/type_int.hpp \
		../glm/glm/detail/setup.hpp \
		../glm/glm/simd/platform.h \
		../glm/glm/detail/type_float.hpp \
		../glm/glm/detail/type_vec.hpp \
		../glm/glm/detail/precision.hpp \
		../glm/glm/detail/type_mat.hpp \
		../glm/glm/vec2.hpp \
		../glm/glm/detail/type_vec2.hpp \
		../glm/glm/detail/_swizzle.hpp \
		../glm/glm/detail/_swizzle_func.hpp \
		../glm/glm/detail/type_vec2.inl \
		../glm/glm/vec3.hpp \
		../glm/glm/detail/type_vec3.hpp \
		../glm/glm/detail/type_vec3.inl \
		../glm/glm/vec4.hpp \
		../glm/glm/detail/type_vec4.hpp \
		../glm/glm/detail/type_vec4.inl \
		../glm/glm/detail/type_vec4_simd.inl \
		../glm/glm/mat2x2.hpp \
		../glm/glm/detail/type_mat2x2.hpp \
		../glm/glm/detail/type_mat2x2.inl \
		../glm/glm/detail/func_matrix.hpp \
		../glm/glm/mat2x3.hpp \
		../glm/glm/detail/type_mat2x3.hpp \
		../glm/glm/detail/type_mat2x3.inl \
		../glm/glm/mat2x4.hpp \
		../glm/glm/detail/type_mat2x4.hpp \
		../glm/glm/detail/type_mat2x4.inl \
		../glm/glm/mat3x2.hpp \
		../glm/glm/detail/type_mat3x2.hpp \
		../glm/glm/detail/type_mat3x2.inl \
		../glm/glm/mat3x3.hpp \
		../glm/glm/detail/type_mat3x3.hpp \
		../glm/glm/detail/type_mat3x3.inl \
		../glm/glm/mat3x4.hpp \
		../glm/glm/detail/type_mat3x4.hpp \
		../glm/glm/detail/type_mat3x4.inl \
		../glm/glm/mat4x2.hpp \
		../glm/glm/detail/type_mat4x2.hpp \
		../glm/glm/detail/type_mat4x2.inl \
		../glm/glm/mat4x3.hpp \
		../glm/glm/detail/type_mat4x3.hpp \
		../glm/glm/detail/type_mat4x3.inl \
		../glm/glm/mat4x4.hpp \
		../glm/glm/detail/type_mat4x4.hpp \
		../glm/glm/detail/type_mat4x4.inl \
		../glm/glm/detail/type_mat4x4_simd.inl \
		../glm/glm/detail/func_matrix.inl \
		../glm/glm/geometric.hpp \
		../glm/glm/detail/func_geometric.hpp \
		../glm/glm/detail/func_geometric.inl \
		../glm/glm/detail/func_exponential.hpp \
		../glm/glm/detail/type_vec1.hpp \
		../glm/glm/detail/type_vec1.inl \
		../glm/glm/detail/func_exponential.inl \
		../glm/glm/detail/func_vector_relational.hpp \
		../glm/glm/detail/func_vector_relational.inl \
		../glm/glm/detail/func_vector_relational_simd.inl \
		../glm/glm/detail/_vectorize.hpp \
		../glm/glm/detail/func_exponential_simd.inl \
		../glm/glm/simd/exponential.h \
		../glm/glm/detail/func_common.hpp \
		../glm/glm/detail/func_common.inl \
		../glm/glm/detail/func_common_simd.inl \
		../glm/glm/simd/common.h \
		../glm/glm/detail/func_geometric_simd.inl \
		../glm/glm/simd/geometric.h \
		../glm/glm/detail/func_matrix_simd.inl \
		../glm/glm/simd/matrix.h \
		../glm/glm/trigonometric.hpp \
		../glm/glm/detail/func_trigonometric.hpp \
		../glm/glm/detail/func_trigonometric.inl \
		../glm/glm/detail/func_trigonometric_simd.inl \
		../glm/glm/exponential.hpp \
		../glm/glm/common.hpp \
		../glm/glm/packing.hpp \
		../glm/glm/detail/func_packing.hpp \
		../glm/glm/detail/func_packing.inl \
		../glm/glm/detail/type_half.hpp \
		../glm/glm/detail/type_half.inl \
		../glm/glm/detail/func_packing_simd.inl \
		../glm/glm/matrix.hpp \
		../glm/glm/vector_relational.hpp \
		../glm/glm/integer.hpp \
		../glm/glm/detail/func_integer.hpp \
		../glm/glm/detail/func_integer.inl \
		../glm/glm/detail/func_integer_simd.inl \
		../glm/glm/simd/integer.h \
		../glm/glm/gtc/matrix_transform.hpp \
		../glm/glm/gtc/constants.hpp \
		../glm/glm/gtc/constants.inl \
		../glm/glm/gtc/matrix_transform.inl \
		../glm/glm/gtc/type_ptr.hpp \
		../glm/glm/gtc/quaternion.hpp \
		../glm/glm/gtc/quaternion.inl \
		../glm/glm/gtc/quaternion_simd.inl \
		../glm/glm/gtc/type_ptr.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

openglwindow.o: src/openglwindow.cpp src/openglwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o openglwindow.o src/openglwindow.cpp

joint.o: src/joint.cpp src/joint.h \
		../trimesh2/include/TriMesh.h \
		../trimesh2/include/Vec.h \
		../trimesh2/include/Box.h \
		../trimesh2/include/strutil.h \
		../trimesh2/include/Color.h \
		../glm/glm/glm.hpp \
		../glm/glm/detail/_fixes.hpp \
		../glm/glm/fwd.hpp \
		../glm/glm/detail/type_int.hpp \
		../glm/glm/detail/setup.hpp \
		../glm/glm/simd/platform.h \
		../glm/glm/detail/type_float.hpp \
		../glm/glm/detail/type_vec.hpp \
		../glm/glm/detail/precision.hpp \
		../glm/glm/detail/type_mat.hpp \
		../glm/glm/vec2.hpp \
		../glm/glm/detail/type_vec2.hpp \
		../glm/glm/detail/_swizzle.hpp \
		../glm/glm/detail/_swizzle_func.hpp \
		../glm/glm/detail/type_vec2.inl \
		../glm/glm/vec3.hpp \
		../glm/glm/detail/type_vec3.hpp \
		../glm/glm/detail/type_vec3.inl \
		../glm/glm/vec4.hpp \
		../glm/glm/detail/type_vec4.hpp \
		../glm/glm/detail/type_vec4.inl \
		../glm/glm/detail/type_vec4_simd.inl \
		../glm/glm/mat2x2.hpp \
		../glm/glm/detail/type_mat2x2.hpp \
		../glm/glm/detail/type_mat2x2.inl \
		../glm/glm/detail/func_matrix.hpp \
		../glm/glm/mat2x3.hpp \
		../glm/glm/detail/type_mat2x3.hpp \
		../glm/glm/detail/type_mat2x3.inl \
		../glm/glm/mat2x4.hpp \
		../glm/glm/detail/type_mat2x4.hpp \
		../glm/glm/detail/type_mat2x4.inl \
		../glm/glm/mat3x2.hpp \
		../glm/glm/detail/type_mat3x2.hpp \
		../glm/glm/detail/type_mat3x2.inl \
		../glm/glm/mat3x3.hpp \
		../glm/glm/detail/type_mat3x3.hpp \
		../glm/glm/detail/type_mat3x3.inl \
		../glm/glm/mat3x4.hpp \
		../glm/glm/detail/type_mat3x4.hpp \
		../glm/glm/detail/type_mat3x4.inl \
		../glm/glm/mat4x2.hpp \
		../glm/glm/detail/type_mat4x2.hpp \
		../glm/glm/detail/type_mat4x2.inl \
		../glm/glm/mat4x3.hpp \
		../glm/glm/detail/type_mat4x3.hpp \
		../glm/glm/detail/type_mat4x3.inl \
		../glm/glm/mat4x4.hpp \
		../glm/glm/detail/type_mat4x4.hpp \
		../glm/glm/detail/type_mat4x4.inl \
		../glm/glm/detail/type_mat4x4_simd.inl \
		../glm/glm/detail/func_matrix.inl \
		../glm/glm/geometric.hpp \
		../glm/glm/detail/func_geometric.hpp \
		../glm/glm/detail/func_geometric.inl \
		../glm/glm/detail/func_exponential.hpp \
		../glm/glm/detail/type_vec1.hpp \
		../glm/glm/detail/type_vec1.inl \
		../glm/glm/detail/func_exponential.inl \
		../glm/glm/detail/func_vector_relational.hpp \
		../glm/glm/detail/func_vector_relational.inl \
		../glm/glm/detail/func_vector_relational_simd.inl \
		../glm/glm/detail/_vectorize.hpp \
		../glm/glm/detail/func_exponential_simd.inl \
		../glm/glm/simd/exponential.h \
		../glm/glm/detail/func_common.hpp \
		../glm/glm/detail/func_common.inl \
		../glm/glm/detail/func_common_simd.inl \
		../glm/glm/simd/common.h \
		../glm/glm/detail/func_geometric_simd.inl \
		../glm/glm/simd/geometric.h \
		../glm/glm/detail/func_matrix_simd.inl \
		../glm/glm/simd/matrix.h \
		../glm/glm/trigonometric.hpp \
		../glm/glm/detail/func_trigonometric.hpp \
		../glm/glm/detail/func_trigonometric.inl \
		../glm/glm/detail/func_trigonometric_simd.inl \
		../glm/glm/exponential.hpp \
		../glm/glm/common.hpp \
		../glm/glm/packing.hpp \
		../glm/glm/detail/func_packing.hpp \
		../glm/glm/detail/func_packing.inl \
		../glm/glm/detail/type_half.hpp \
		../glm/glm/detail/type_half.inl \
		../glm/glm/detail/func_packing_simd.inl \
		../glm/glm/matrix.hpp \
		../glm/glm/vector_relational.hpp \
		../glm/glm/integer.hpp \
		../glm/glm/detail/func_integer.hpp \
		../glm/glm/detail/func_integer.inl \
		../glm/glm/detail/func_integer_simd.inl \
		../glm/glm/simd/integer.h \
		../glm/glm/gtc/matrix_transform.hpp \
		../glm/glm/gtc/constants.hpp \
		../glm/glm/gtc/constants.inl \
		../glm/glm/gtc/matrix_transform.inl \
		../glm/glm/gtc/type_ptr.hpp \
		../glm/glm/gtc/quaternion.hpp \
		../glm/glm/gtc/quaternion.inl \
		../glm/glm/gtc/quaternion_simd.inl \
		../glm/glm/gtc/type_ptr.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o joint.o src/joint.cpp

glshaderwindow.o: src/glshaderwindow.cpp src/glshaderwindow.h \
		src/openglwindow.h \
		../trimesh2/include/TriMesh.h \
		../trimesh2/include/Vec.h \
		../trimesh2/include/Box.h \
		../trimesh2/include/strutil.h \
		../trimesh2/include/Color.h \
		src/joint.h \
		../glm/glm/glm.hpp \
		../glm/glm/detail/_fixes.hpp \
		../glm/glm/fwd.hpp \
		../glm/glm/detail/type_int.hpp \
		../glm/glm/detail/setup.hpp \
		../glm/glm/simd/platform.h \
		../glm/glm/detail/type_float.hpp \
		../glm/glm/detail/type_vec.hpp \
		../glm/glm/detail/precision.hpp \
		../glm/glm/detail/type_mat.hpp \
		../glm/glm/vec2.hpp \
		../glm/glm/detail/type_vec2.hpp \
		../glm/glm/detail/_swizzle.hpp \
		../glm/glm/detail/_swizzle_func.hpp \
		../glm/glm/detail/type_vec2.inl \
		../glm/glm/vec3.hpp \
		../glm/glm/detail/type_vec3.hpp \
		../glm/glm/detail/type_vec3.inl \
		../glm/glm/vec4.hpp \
		../glm/glm/detail/type_vec4.hpp \
		../glm/glm/detail/type_vec4.inl \
		../glm/glm/detail/type_vec4_simd.inl \
		../glm/glm/mat2x2.hpp \
		../glm/glm/detail/type_mat2x2.hpp \
		../glm/glm/detail/type_mat2x2.inl \
		../glm/glm/detail/func_matrix.hpp \
		../glm/glm/mat2x3.hpp \
		../glm/glm/detail/type_mat2x3.hpp \
		../glm/glm/detail/type_mat2x3.inl \
		../glm/glm/mat2x4.hpp \
		../glm/glm/detail/type_mat2x4.hpp \
		../glm/glm/detail/type_mat2x4.inl \
		../glm/glm/mat3x2.hpp \
		../glm/glm/detail/type_mat3x2.hpp \
		../glm/glm/detail/type_mat3x2.inl \
		../glm/glm/mat3x3.hpp \
		../glm/glm/detail/type_mat3x3.hpp \
		../glm/glm/detail/type_mat3x3.inl \
		../glm/glm/mat3x4.hpp \
		../glm/glm/detail/type_mat3x4.hpp \
		../glm/glm/detail/type_mat3x4.inl \
		../glm/glm/mat4x2.hpp \
		../glm/glm/detail/type_mat4x2.hpp \
		../glm/glm/detail/type_mat4x2.inl \
		../glm/glm/mat4x3.hpp \
		../glm/glm/detail/type_mat4x3.hpp \
		../glm/glm/detail/type_mat4x3.inl \
		../glm/glm/mat4x4.hpp \
		../glm/glm/detail/type_mat4x4.hpp \
		../glm/glm/detail/type_mat4x4.inl \
		../glm/glm/detail/type_mat4x4_simd.inl \
		../glm/glm/detail/func_matrix.inl \
		../glm/glm/geometric.hpp \
		../glm/glm/detail/func_geometric.hpp \
		../glm/glm/detail/func_geometric.inl \
		../glm/glm/detail/func_exponential.hpp \
		../glm/glm/detail/type_vec1.hpp \
		../glm/glm/detail/type_vec1.inl \
		../glm/glm/detail/func_exponential.inl \
		../glm/glm/detail/func_vector_relational.hpp \
		../glm/glm/detail/func_vector_relational.inl \
		../glm/glm/detail/func_vector_relational_simd.inl \
		../glm/glm/detail/_vectorize.hpp \
		../glm/glm/detail/func_exponential_simd.inl \
		../glm/glm/simd/exponential.h \
		../glm/glm/detail/func_common.hpp \
		../glm/glm/detail/func_common.inl \
		../glm/glm/detail/func_common_simd.inl \
		../glm/glm/simd/common.h \
		../glm/glm/detail/func_geometric_simd.inl \
		../glm/glm/simd/geometric.h \
		../glm/glm/detail/func_matrix_simd.inl \
		../glm/glm/simd/matrix.h \
		../glm/glm/trigonometric.hpp \
		../glm/glm/detail/func_trigonometric.hpp \
		../glm/glm/detail/func_trigonometric.inl \
		../glm/glm/detail/func_trigonometric_simd.inl \
		../glm/glm/exponential.hpp \
		../glm/glm/common.hpp \
		../glm/glm/packing.hpp \
		../glm/glm/detail/func_packing.hpp \
		../glm/glm/detail/func_packing.inl \
		../glm/glm/detail/type_half.hpp \
		../glm/glm/detail/type_half.inl \
		../glm/glm/detail/func_packing_simd.inl \
		../glm/glm/matrix.hpp \
		../glm/glm/vector_relational.hpp \
		../glm/glm/integer.hpp \
		../glm/glm/detail/func_integer.hpp \
		../glm/glm/detail/func_integer.inl \
		../glm/glm/detail/func_integer_simd.inl \
		../glm/glm/simd/integer.h \
		../glm/glm/gtc/matrix_transform.hpp \
		../glm/glm/gtc/constants.hpp \
		../glm/glm/gtc/constants.inl \
		../glm/glm/gtc/matrix_transform.inl \
		../glm/glm/gtc/type_ptr.hpp \
		../glm/glm/gtc/quaternion.hpp \
		../glm/glm/gtc/quaternion.inl \
		../glm/glm/gtc/quaternion_simd.inl \
		../glm/glm/gtc/type_ptr.inl \
		src/perlinNoise.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glshaderwindow.o src/glshaderwindow.cpp

moc_openglwindow.o: moc_openglwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_openglwindow.o moc_openglwindow.cpp

moc_glshaderwindow.o: moc_glshaderwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glshaderwindow.o moc_glshaderwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

